archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make provider
builds:
  - binary: pulumi-resource-statuscake
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/pulumiverse/pulumi-statuscake/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-statuscake/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
