// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    public static class GetContactGroup
    {
        public static Task<GetContactGroupResult> InvokeAsync(GetContactGroupArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetContactGroupResult>("statuscake:index/getContactGroup:getContactGroup", args ?? new GetContactGroupArgs(), options.WithDefaults());

        public static Output<GetContactGroupResult> Invoke(GetContactGroupInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetContactGroupResult>("statuscake:index/getContactGroup:getContactGroup", args ?? new GetContactGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetContactGroupArgs : Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetContactGroupArgs()
        {
        }
    }

    public sealed class GetContactGroupInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetContactGroupInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetContactGroupResult
    {
        public readonly ImmutableArray<string> EmailAddresses;
        public readonly string Id;
        public readonly ImmutableArray<string> Integrations;
        public readonly ImmutableArray<string> MobileNumbers;
        public readonly string Name;
        public readonly string PingUrl;

        [OutputConstructor]
        private GetContactGroupResult(
            ImmutableArray<string> emailAddresses,

            string id,

            ImmutableArray<string> integrations,

            ImmutableArray<string> mobileNumbers,

            string name,

            string pingUrl)
        {
            EmailAddresses = emailAddresses;
            Id = id;
            Integrations = integrations;
            MobileNumbers = mobileNumbers;
            Name = name;
            PingUrl = pingUrl;
        }
    }
}
