// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    public static class GetStatuscakeUptimeMonitoringLocations
    {
        public static Task<GetStatuscakeUptimeMonitoringLocationsResult> InvokeAsync(GetStatuscakeUptimeMonitoringLocationsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetStatuscakeUptimeMonitoringLocationsResult>("statuscake:index/getStatuscakeUptimeMonitoringLocations:getStatuscakeUptimeMonitoringLocations", args ?? new GetStatuscakeUptimeMonitoringLocationsArgs(), options.WithDefaults());

        public static Output<GetStatuscakeUptimeMonitoringLocationsResult> Invoke(GetStatuscakeUptimeMonitoringLocationsInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetStatuscakeUptimeMonitoringLocationsResult>("statuscake:index/getStatuscakeUptimeMonitoringLocations:getStatuscakeUptimeMonitoringLocations", args ?? new GetStatuscakeUptimeMonitoringLocationsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetStatuscakeUptimeMonitoringLocationsArgs : Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public string? RegionCode { get; set; }

        public GetStatuscakeUptimeMonitoringLocationsArgs()
        {
        }
    }

    public sealed class GetStatuscakeUptimeMonitoringLocationsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public Input<string>? RegionCode { get; set; }

        public GetStatuscakeUptimeMonitoringLocationsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetStatuscakeUptimeMonitoringLocationsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetStatuscakeUptimeMonitoringLocationsLocationResult> Locations;
        public readonly string? RegionCode;

        [OutputConstructor]
        private GetStatuscakeUptimeMonitoringLocationsResult(
            string id,

            ImmutableArray<Outputs.GetStatuscakeUptimeMonitoringLocationsLocationResult> locations,

            string? regionCode)
        {
            Id = id;
            Locations = locations;
            RegionCode = regionCode;
        }
    }
}
