// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    public static class GetStatuscakePagespeedMonitoringLocations
    {
        public static Task<GetStatuscakePagespeedMonitoringLocationsResult> InvokeAsync(GetStatuscakePagespeedMonitoringLocationsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetStatuscakePagespeedMonitoringLocationsResult>("statuscake:index/getStatuscakePagespeedMonitoringLocations:getStatuscakePagespeedMonitoringLocations", args ?? new GetStatuscakePagespeedMonitoringLocationsArgs(), options.WithDefaults());

        public static Output<GetStatuscakePagespeedMonitoringLocationsResult> Invoke(GetStatuscakePagespeedMonitoringLocationsInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetStatuscakePagespeedMonitoringLocationsResult>("statuscake:index/getStatuscakePagespeedMonitoringLocations:getStatuscakePagespeedMonitoringLocations", args ?? new GetStatuscakePagespeedMonitoringLocationsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetStatuscakePagespeedMonitoringLocationsArgs : Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public string? RegionCode { get; set; }

        public GetStatuscakePagespeedMonitoringLocationsArgs()
        {
        }
    }

    public sealed class GetStatuscakePagespeedMonitoringLocationsInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("regionCode")]
        public Input<string>? RegionCode { get; set; }

        public GetStatuscakePagespeedMonitoringLocationsInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetStatuscakePagespeedMonitoringLocationsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetStatuscakePagespeedMonitoringLocationsLocationResult> Locations;
        public readonly string? RegionCode;

        [OutputConstructor]
        private GetStatuscakePagespeedMonitoringLocationsResult(
            string id,

            ImmutableArray<Outputs.GetStatuscakePagespeedMonitoringLocationsLocationResult> locations,

            string? regionCode)
        {
            Id = id;
            Locations = locations;
            RegionCode = regionCode;
        }
    }
}
