// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake
{
    [StatuscakeResourceType("statuscake:index/statuscakeContactGroup:StatuscakeContactGroup")]
    public partial class StatuscakeContactGroup : Pulumi.CustomResource
    {
        /// <summary>
        /// List of email addresses
        /// </summary>
        [Output("emailAddresses")]
        public Output<ImmutableArray<string>> EmailAddresses { get; private set; } = null!;

        /// <summary>
        /// List of integration IDs
        /// </summary>
        [Output("integrations")]
        public Output<ImmutableArray<string>> Integrations { get; private set; } = null!;

        /// <summary>
        /// List of international format mobile phone numbers
        /// </summary>
        [Output("mobileNumbers")]
        public Output<ImmutableArray<string>> MobileNumbers { get; private set; } = null!;

        /// <summary>
        /// Name of the contact group
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
        /// </summary>
        [Output("pingUrl")]
        public Output<string?> PingUrl { get; private set; } = null!;


        /// <summary>
        /// Create a StatuscakeContactGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StatuscakeContactGroup(string name, StatuscakeContactGroupArgs? args = null, CustomResourceOptions? options = null)
            : base("statuscake:index/statuscakeContactGroup:StatuscakeContactGroup", name, args ?? new StatuscakeContactGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StatuscakeContactGroup(string name, Input<string> id, StatuscakeContactGroupState? state = null, CustomResourceOptions? options = null)
            : base("statuscake:index/statuscakeContactGroup:StatuscakeContactGroup", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StatuscakeContactGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StatuscakeContactGroup Get(string name, Input<string> id, StatuscakeContactGroupState? state = null, CustomResourceOptions? options = null)
        {
            return new StatuscakeContactGroup(name, id, state, options);
        }
    }

    public sealed class StatuscakeContactGroupArgs : Pulumi.ResourceArgs
    {
        [Input("emailAddresses")]
        private InputList<string>? _emailAddresses;

        /// <summary>
        /// List of email addresses
        /// </summary>
        public InputList<string> EmailAddresses
        {
            get => _emailAddresses ?? (_emailAddresses = new InputList<string>());
            set => _emailAddresses = value;
        }

        [Input("integrations")]
        private InputList<string>? _integrations;

        /// <summary>
        /// List of integration IDs
        /// </summary>
        public InputList<string> Integrations
        {
            get => _integrations ?? (_integrations = new InputList<string>());
            set => _integrations = value;
        }

        [Input("mobileNumbers")]
        private InputList<string>? _mobileNumbers;

        /// <summary>
        /// List of international format mobile phone numbers
        /// </summary>
        public InputList<string> MobileNumbers
        {
            get => _mobileNumbers ?? (_mobileNumbers = new InputList<string>());
            set => _mobileNumbers = value;
        }

        /// <summary>
        /// Name of the contact group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
        /// </summary>
        [Input("pingUrl")]
        public Input<string>? PingUrl { get; set; }

        public StatuscakeContactGroupArgs()
        {
        }
    }

    public sealed class StatuscakeContactGroupState : Pulumi.ResourceArgs
    {
        [Input("emailAddresses")]
        private InputList<string>? _emailAddresses;

        /// <summary>
        /// List of email addresses
        /// </summary>
        public InputList<string> EmailAddresses
        {
            get => _emailAddresses ?? (_emailAddresses = new InputList<string>());
            set => _emailAddresses = value;
        }

        [Input("integrations")]
        private InputList<string>? _integrations;

        /// <summary>
        /// List of integration IDs
        /// </summary>
        public InputList<string> Integrations
        {
            get => _integrations ?? (_integrations = new InputList<string>());
            set => _integrations = value;
        }

        [Input("mobileNumbers")]
        private InputList<string>? _mobileNumbers;

        /// <summary>
        /// List of international format mobile phone numbers
        /// </summary>
        public InputList<string> MobileNumbers
        {
            get => _mobileNumbers ?? (_mobileNumbers = new InputList<string>());
            set => _mobileNumbers = value;
        }

        /// <summary>
        /// Name of the contact group
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
        /// </summary>
        [Input("pingUrl")]
        public Input<string>? PingUrl { get; set; }

        public StatuscakeContactGroupState()
        {
        }
    }
}
