// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuscake

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupStatuscakeContactGroup(ctx *pulumi.Context, args *LookupStatuscakeContactGroupArgs, opts ...pulumi.InvokeOption) (*LookupStatuscakeContactGroupResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupStatuscakeContactGroupResult
	err := ctx.Invoke("statuscake:index/getStatuscakeContactGroup:getStatuscakeContactGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStatuscakeContactGroup.
type LookupStatuscakeContactGroupArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getStatuscakeContactGroup.
type LookupStatuscakeContactGroupResult struct {
	EmailAddresses []string `pulumi:"emailAddresses"`
	Id             string   `pulumi:"id"`
	Integrations   []string `pulumi:"integrations"`
	MobileNumbers  []string `pulumi:"mobileNumbers"`
	Name           string   `pulumi:"name"`
	PingUrl        string   `pulumi:"pingUrl"`
}

func LookupStatuscakeContactGroupOutput(ctx *pulumi.Context, args LookupStatuscakeContactGroupOutputArgs, opts ...pulumi.InvokeOption) LookupStatuscakeContactGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupStatuscakeContactGroupResult, error) {
			args := v.(LookupStatuscakeContactGroupArgs)
			r, err := LookupStatuscakeContactGroup(ctx, &args, opts...)
			var s LookupStatuscakeContactGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupStatuscakeContactGroupResultOutput)
}

// A collection of arguments for invoking getStatuscakeContactGroup.
type LookupStatuscakeContactGroupOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupStatuscakeContactGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStatuscakeContactGroupArgs)(nil)).Elem()
}

// A collection of values returned by getStatuscakeContactGroup.
type LookupStatuscakeContactGroupResultOutput struct{ *pulumi.OutputState }

func (LookupStatuscakeContactGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStatuscakeContactGroupResult)(nil)).Elem()
}

func (o LookupStatuscakeContactGroupResultOutput) ToLookupStatuscakeContactGroupResultOutput() LookupStatuscakeContactGroupResultOutput {
	return o
}

func (o LookupStatuscakeContactGroupResultOutput) ToLookupStatuscakeContactGroupResultOutputWithContext(ctx context.Context) LookupStatuscakeContactGroupResultOutput {
	return o
}

func (o LookupStatuscakeContactGroupResultOutput) EmailAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) []string { return v.EmailAddresses }).(pulumi.StringArrayOutput)
}

func (o LookupStatuscakeContactGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupStatuscakeContactGroupResultOutput) Integrations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) []string { return v.Integrations }).(pulumi.StringArrayOutput)
}

func (o LookupStatuscakeContactGroupResultOutput) MobileNumbers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) []string { return v.MobileNumbers }).(pulumi.StringArrayOutput)
}

func (o LookupStatuscakeContactGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupStatuscakeContactGroupResultOutput) PingUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStatuscakeContactGroupResult) string { return v.PingUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupStatuscakeContactGroupResultOutput{})
}
