// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuscake

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "statuscake:index/statuscakeContactGroup:StatuscakeContactGroup":
		r = &StatuscakeContactGroup{}
	case "statuscake:index/statuscakeMaintenanceWindow:StatuscakeMaintenanceWindow":
		r = &StatuscakeMaintenanceWindow{}
	case "statuscake:index/statuscakePagespeedCheck:StatuscakePagespeedCheck":
		r = &StatuscakePagespeedCheck{}
	case "statuscake:index/statuscakeSslCheck:StatuscakeSslCheck":
		r = &StatuscakeSslCheck{}
	case "statuscake:index/statuscakeUptimeCheck:StatuscakeUptimeCheck":
		r = &StatuscakeUptimeCheck{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:statuscake" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"statuscake",
		"index/statuscakeContactGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"statuscake",
		"index/statuscakeMaintenanceWindow",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"statuscake",
		"index/statuscakePagespeedCheck",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"statuscake",
		"index/statuscakeSslCheck",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"statuscake",
		"index/statuscakeUptimeCheck",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"statuscake",
		&pkg{version},
	)
}
