// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuscake

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the statuscake package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
	ApiToken pulumi.StringPtrOutput `pulumi:"apiToken"`
	// Custom endpoint to which request will be made. This can also be provided as an environment variable
	// `STATUCAKE_CUSTOM_ENDPOINT`
	StatuscakeCustomEndpoint pulumi.StringPtrOutput `pulumi:"statuscakeCustomEndpoint"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if isZero(args.ApiToken) {
		args.ApiToken = pulumi.StringPtr(getEnvOrDefault("", nil, "STATUSCAKE_API_TOKEN").(string))
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrOutput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
	})
	opts = append(opts, secrets)
	opts = pkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:statuscake", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
	ApiToken *string `pulumi:"apiToken"`
	// Maximum backoff period in seconds after failed API calls. This can also be provided as an environment variable
	// `STATUSCAKE_MAX_BACKOFF`
	MaxBackoff *int `pulumi:"maxBackoff"`
	// Minimum backoff period in seconds after failed API calls. This can also be provided as an environment variable
	// `STATUSCAKE_MIN_BACKOFF`
	MinBackoff *int `pulumi:"minBackoff"`
	// Maximum number of retries to perform when an API request fails. This can also be provided as an environment variable
	// `STATUSCAKE_RETRIES`
	Retries *int `pulumi:"retries"`
	// RPS limit to apply when making calls to the API. This can also be provided as an environment variable `STATUSCAKE_RPS`
	Rps *int `pulumi:"rps"`
	// Custom endpoint to which request will be made. This can also be provided as an environment variable
	// `STATUCAKE_CUSTOM_ENDPOINT`
	StatuscakeCustomEndpoint *string `pulumi:"statuscakeCustomEndpoint"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
	ApiToken pulumi.StringPtrInput
	// Maximum backoff period in seconds after failed API calls. This can also be provided as an environment variable
	// `STATUSCAKE_MAX_BACKOFF`
	MaxBackoff pulumi.IntPtrInput
	// Minimum backoff period in seconds after failed API calls. This can also be provided as an environment variable
	// `STATUSCAKE_MIN_BACKOFF`
	MinBackoff pulumi.IntPtrInput
	// Maximum number of retries to perform when an API request fails. This can also be provided as an environment variable
	// `STATUSCAKE_RETRIES`
	Retries pulumi.IntPtrInput
	// RPS limit to apply when making calls to the API. This can also be provided as an environment variable `STATUSCAKE_RPS`
	Rps pulumi.IntPtrInput
	// Custom endpoint to which request will be made. This can also be provided as an environment variable
	// `STATUCAKE_CUSTOM_ENDPOINT`
	StatuscakeCustomEndpoint pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
func (o ProviderOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

// Custom endpoint to which request will be made. This can also be provided as an environment variable
// `STATUCAKE_CUSTOM_ENDPOINT`
func (o ProviderOutput) StatuscakeCustomEndpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.StatuscakeCustomEndpoint }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
