// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package statuscake

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StatuscakeContactGroup struct {
	pulumi.CustomResourceState

	// List of email addresses
	EmailAddresses pulumi.StringArrayOutput `pulumi:"emailAddresses"`
	// List of integration IDs
	Integrations pulumi.StringArrayOutput `pulumi:"integrations"`
	// List of international format mobile phone numbers
	MobileNumbers pulumi.StringArrayOutput `pulumi:"mobileNumbers"`
	// Name of the contact group
	Name pulumi.StringOutput `pulumi:"name"`
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingUrl pulumi.StringPtrOutput `pulumi:"pingUrl"`
}

// NewStatuscakeContactGroup registers a new resource with the given unique name, arguments, and options.
func NewStatuscakeContactGroup(ctx *pulumi.Context,
	name string, args *StatuscakeContactGroupArgs, opts ...pulumi.ResourceOption) (*StatuscakeContactGroup, error) {
	if args == nil {
		args = &StatuscakeContactGroupArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource StatuscakeContactGroup
	err := ctx.RegisterResource("statuscake:index/statuscakeContactGroup:StatuscakeContactGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStatuscakeContactGroup gets an existing StatuscakeContactGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStatuscakeContactGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StatuscakeContactGroupState, opts ...pulumi.ResourceOption) (*StatuscakeContactGroup, error) {
	var resource StatuscakeContactGroup
	err := ctx.ReadResource("statuscake:index/statuscakeContactGroup:StatuscakeContactGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StatuscakeContactGroup resources.
type statuscakeContactGroupState struct {
	// List of email addresses
	EmailAddresses []string `pulumi:"emailAddresses"`
	// List of integration IDs
	Integrations []string `pulumi:"integrations"`
	// List of international format mobile phone numbers
	MobileNumbers []string `pulumi:"mobileNumbers"`
	// Name of the contact group
	Name *string `pulumi:"name"`
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingUrl *string `pulumi:"pingUrl"`
}

type StatuscakeContactGroupState struct {
	// List of email addresses
	EmailAddresses pulumi.StringArrayInput
	// List of integration IDs
	Integrations pulumi.StringArrayInput
	// List of international format mobile phone numbers
	MobileNumbers pulumi.StringArrayInput
	// Name of the contact group
	Name pulumi.StringPtrInput
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingUrl pulumi.StringPtrInput
}

func (StatuscakeContactGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*statuscakeContactGroupState)(nil)).Elem()
}

type statuscakeContactGroupArgs struct {
	// List of email addresses
	EmailAddresses []string `pulumi:"emailAddresses"`
	// List of integration IDs
	Integrations []string `pulumi:"integrations"`
	// List of international format mobile phone numbers
	MobileNumbers []string `pulumi:"mobileNumbers"`
	// Name of the contact group
	Name *string `pulumi:"name"`
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingUrl *string `pulumi:"pingUrl"`
}

// The set of arguments for constructing a StatuscakeContactGroup resource.
type StatuscakeContactGroupArgs struct {
	// List of email addresses
	EmailAddresses pulumi.StringArrayInput
	// List of integration IDs
	Integrations pulumi.StringArrayInput
	// List of international format mobile phone numbers
	MobileNumbers pulumi.StringArrayInput
	// Name of the contact group
	Name pulumi.StringPtrInput
	// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
	PingUrl pulumi.StringPtrInput
}

func (StatuscakeContactGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*statuscakeContactGroupArgs)(nil)).Elem()
}

type StatuscakeContactGroupInput interface {
	pulumi.Input

	ToStatuscakeContactGroupOutput() StatuscakeContactGroupOutput
	ToStatuscakeContactGroupOutputWithContext(ctx context.Context) StatuscakeContactGroupOutput
}

func (*StatuscakeContactGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**StatuscakeContactGroup)(nil)).Elem()
}

func (i *StatuscakeContactGroup) ToStatuscakeContactGroupOutput() StatuscakeContactGroupOutput {
	return i.ToStatuscakeContactGroupOutputWithContext(context.Background())
}

func (i *StatuscakeContactGroup) ToStatuscakeContactGroupOutputWithContext(ctx context.Context) StatuscakeContactGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StatuscakeContactGroupOutput)
}

// StatuscakeContactGroupArrayInput is an input type that accepts StatuscakeContactGroupArray and StatuscakeContactGroupArrayOutput values.
// You can construct a concrete instance of `StatuscakeContactGroupArrayInput` via:
//
//	StatuscakeContactGroupArray{ StatuscakeContactGroupArgs{...} }
type StatuscakeContactGroupArrayInput interface {
	pulumi.Input

	ToStatuscakeContactGroupArrayOutput() StatuscakeContactGroupArrayOutput
	ToStatuscakeContactGroupArrayOutputWithContext(context.Context) StatuscakeContactGroupArrayOutput
}

type StatuscakeContactGroupArray []StatuscakeContactGroupInput

func (StatuscakeContactGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StatuscakeContactGroup)(nil)).Elem()
}

func (i StatuscakeContactGroupArray) ToStatuscakeContactGroupArrayOutput() StatuscakeContactGroupArrayOutput {
	return i.ToStatuscakeContactGroupArrayOutputWithContext(context.Background())
}

func (i StatuscakeContactGroupArray) ToStatuscakeContactGroupArrayOutputWithContext(ctx context.Context) StatuscakeContactGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StatuscakeContactGroupArrayOutput)
}

// StatuscakeContactGroupMapInput is an input type that accepts StatuscakeContactGroupMap and StatuscakeContactGroupMapOutput values.
// You can construct a concrete instance of `StatuscakeContactGroupMapInput` via:
//
//	StatuscakeContactGroupMap{ "key": StatuscakeContactGroupArgs{...} }
type StatuscakeContactGroupMapInput interface {
	pulumi.Input

	ToStatuscakeContactGroupMapOutput() StatuscakeContactGroupMapOutput
	ToStatuscakeContactGroupMapOutputWithContext(context.Context) StatuscakeContactGroupMapOutput
}

type StatuscakeContactGroupMap map[string]StatuscakeContactGroupInput

func (StatuscakeContactGroupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StatuscakeContactGroup)(nil)).Elem()
}

func (i StatuscakeContactGroupMap) ToStatuscakeContactGroupMapOutput() StatuscakeContactGroupMapOutput {
	return i.ToStatuscakeContactGroupMapOutputWithContext(context.Background())
}

func (i StatuscakeContactGroupMap) ToStatuscakeContactGroupMapOutputWithContext(ctx context.Context) StatuscakeContactGroupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StatuscakeContactGroupMapOutput)
}

type StatuscakeContactGroupOutput struct{ *pulumi.OutputState }

func (StatuscakeContactGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StatuscakeContactGroup)(nil)).Elem()
}

func (o StatuscakeContactGroupOutput) ToStatuscakeContactGroupOutput() StatuscakeContactGroupOutput {
	return o
}

func (o StatuscakeContactGroupOutput) ToStatuscakeContactGroupOutputWithContext(ctx context.Context) StatuscakeContactGroupOutput {
	return o
}

// List of email addresses
func (o StatuscakeContactGroupOutput) EmailAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StatuscakeContactGroup) pulumi.StringArrayOutput { return v.EmailAddresses }).(pulumi.StringArrayOutput)
}

// List of integration IDs
func (o StatuscakeContactGroupOutput) Integrations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StatuscakeContactGroup) pulumi.StringArrayOutput { return v.Integrations }).(pulumi.StringArrayOutput)
}

// List of international format mobile phone numbers
func (o StatuscakeContactGroupOutput) MobileNumbers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StatuscakeContactGroup) pulumi.StringArrayOutput { return v.MobileNumbers }).(pulumi.StringArrayOutput)
}

// Name of the contact group
func (o StatuscakeContactGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StatuscakeContactGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// URL or IP address of an endpoint to push uptime events. Currently this only supports HTTP GET endpoints
func (o StatuscakeContactGroupOutput) PingUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StatuscakeContactGroup) pulumi.StringPtrOutput { return v.PingUrl }).(pulumi.StringPtrOutput)
}

type StatuscakeContactGroupArrayOutput struct{ *pulumi.OutputState }

func (StatuscakeContactGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StatuscakeContactGroup)(nil)).Elem()
}

func (o StatuscakeContactGroupArrayOutput) ToStatuscakeContactGroupArrayOutput() StatuscakeContactGroupArrayOutput {
	return o
}

func (o StatuscakeContactGroupArrayOutput) ToStatuscakeContactGroupArrayOutputWithContext(ctx context.Context) StatuscakeContactGroupArrayOutput {
	return o
}

func (o StatuscakeContactGroupArrayOutput) Index(i pulumi.IntInput) StatuscakeContactGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *StatuscakeContactGroup {
		return vs[0].([]*StatuscakeContactGroup)[vs[1].(int)]
	}).(StatuscakeContactGroupOutput)
}

type StatuscakeContactGroupMapOutput struct{ *pulumi.OutputState }

func (StatuscakeContactGroupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StatuscakeContactGroup)(nil)).Elem()
}

func (o StatuscakeContactGroupMapOutput) ToStatuscakeContactGroupMapOutput() StatuscakeContactGroupMapOutput {
	return o
}

func (o StatuscakeContactGroupMapOutput) ToStatuscakeContactGroupMapOutputWithContext(ctx context.Context) StatuscakeContactGroupMapOutput {
	return o
}

func (o StatuscakeContactGroupMapOutput) MapIndex(k pulumi.StringInput) StatuscakeContactGroupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *StatuscakeContactGroup {
		return vs[0].(map[string]*StatuscakeContactGroup)[vs[1].(string)]
	}).(StatuscakeContactGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StatuscakeContactGroupInput)(nil)).Elem(), &StatuscakeContactGroup{})
	pulumi.RegisterInputType(reflect.TypeOf((*StatuscakeContactGroupArrayInput)(nil)).Elem(), StatuscakeContactGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*StatuscakeContactGroupMapInput)(nil)).Elem(), StatuscakeContactGroupMap{})
	pulumi.RegisterOutputType(StatuscakeContactGroupOutput{})
	pulumi.RegisterOutputType(StatuscakeContactGroupArrayOutput{})
	pulumi.RegisterOutputType(StatuscakeContactGroupMapOutput{})
}
