// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class StatuscakeUptimeCheckTcpCheck
    {
        public readonly Outputs.StatuscakeUptimeCheckTcpCheckAuthentication? Authentication;
        public readonly int Port;
        public readonly string? Protocol;
        public readonly int? Timeout;

        [OutputConstructor]
        private StatuscakeUptimeCheckTcpCheck(
            Outputs.StatuscakeUptimeCheckTcpCheckAuthentication? authentication,

            int port,

            string? protocol,

            int? timeout)
        {
            Authentication = authentication;
            Port = port;
            Protocol = protocol;
            Timeout = timeout;
        }
    }
}
