// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Outputs
{

    [OutputType]
    public sealed class UptimeCheckMonitoredResource
    {
        public readonly string Address;
        public readonly string? Host;

        [OutputConstructor]
        private UptimeCheckMonitoredResource(
            string address,

            string? host)
        {
            Address = address;
            Host = host;
        }
    }
}
