# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiToken: Optional[str]
"""
The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
"""

maxBackoff: Optional[int]
"""
Maximum backoff period in seconds after failed API calls. This can also be provided as an environment variable
`STATUSCAKE_MAX_BACKOFF`
"""

minBackoff: Optional[int]
"""
Minimum backoff period in seconds after failed API calls. This can also be provided as an environment variable
`STATUSCAKE_MIN_BACKOFF`
"""

retries: Optional[int]
"""
Maximum number of retries to perform when an API request fails. This can also be provided as an environment variable
`STATUSCAKE_RETRIES`
"""

rps: Optional[int]
"""
RPS limit to apply when making calls to the API. This can also be provided as an environment variable `STATUSCAKE_RPS`
"""

statuscakeCustomEndpoint: Optional[str]
"""
Custom endpoint to which request will be made. This can also be provided as an environment variable
`STATUCAKE_CUSTOM_ENDPOINT`
"""

