# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('statuscake')


class _ExportableConfig(types.ModuleType):
    @property
    def api_token(self) -> Optional[str]:
        """
        The API token for operations. This can also be provided as an environment variable `STATUSCAKE_API_TOKEN`
        """
        return __config__.get('apiToken') or _utilities.get_env('STATUSCAKE_API_TOKEN')

    @property
    def max_backoff(self) -> Optional[int]:
        """
        Maximum backoff period in seconds after failed API calls. This can also be provided as an environment variable
        `STATUSCAKE_MAX_BACKOFF`
        """
        return __config__.get_int('maxBackoff')

    @property
    def min_backoff(self) -> Optional[int]:
        """
        Minimum backoff period in seconds after failed API calls. This can also be provided as an environment variable
        `STATUSCAKE_MIN_BACKOFF`
        """
        return __config__.get_int('minBackoff')

    @property
    def retries(self) -> Optional[int]:
        """
        Maximum number of retries to perform when an API request fails. This can also be provided as an environment variable
        `STATUSCAKE_RETRIES`
        """
        return __config__.get_int('retries')

    @property
    def rps(self) -> Optional[int]:
        """
        RPS limit to apply when making calls to the API. This can also be provided as an environment variable `STATUSCAKE_RPS`
        """
        return __config__.get_int('rps')

    @property
    def statuscake_custom_endpoint(self) -> Optional[str]:
        """
        Custom endpoint to which request will be made. This can also be provided as an environment variable
        `STATUCAKE_CUSTOM_ENDPOINT`
        """
        return __config__.get('statuscakeCustomEndpoint')

