# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_statuscake_contact_group import *
from .get_statuscake_pagespeed_monitoring_locations import *
from .get_statuscake_uptime_monitoring_locations import *
from .provider import *
from .statuscake_contact_group import *
from .statuscake_maintenance_window import *
from .statuscake_pagespeed_check import *
from .statuscake_ssl_check import *
from .statuscake_uptime_check import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_statuscake.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumiverse_statuscake.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "statuscake",
  "mod": "index/statuscakeContactGroup",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/statuscakeContactGroup:StatuscakeContactGroup": "StatuscakeContactGroup"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/statuscakeMaintenanceWindow",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/statuscakeMaintenanceWindow:StatuscakeMaintenanceWindow": "StatuscakeMaintenanceWindow"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/statuscakePagespeedCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/statuscakePagespeedCheck:StatuscakePagespeedCheck": "StatuscakePagespeedCheck"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/statuscakeSslCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/statuscakeSslCheck:StatuscakeSslCheck": "StatuscakeSslCheck"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/statuscakeUptimeCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/statuscakeUptimeCheck:StatuscakeUptimeCheck": "StatuscakeUptimeCheck"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "statuscake",
  "token": "pulumi:providers:statuscake",
  "fqn": "pulumiverse_statuscake",
  "class": "Provider"
 }
]
"""
)
