# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .contact_group import *
from .get_contact_group import *
from .get_pagespeed_monitoring_locations import *
from .get_uptime_monitoring_locations import *
from .maintenance_window import *
from .pagespeed_check import *
from .provider import *
from .ssl_check import *
from .uptime_check import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_statuscake.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumiverse_statuscake.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "statuscake",
  "mod": "index/contactGroup",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/contactGroup:ContactGroup": "ContactGroup"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/maintenanceWindow",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/maintenanceWindow:MaintenanceWindow": "MaintenanceWindow"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/pagespeedCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/pagespeedCheck:PagespeedCheck": "PagespeedCheck"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/sslCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/sslCheck:SslCheck": "SslCheck"
  }
 },
 {
  "pkg": "statuscake",
  "mod": "index/uptimeCheck",
  "fqn": "pulumiverse_statuscake",
  "classes": {
   "statuscake:index/uptimeCheck:UptimeCheck": "UptimeCheck"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "statuscake",
  "token": "pulumi:providers:statuscake",
  "fqn": "pulumiverse_statuscake",
  "class": "Provider"
 }
]
"""
)
