// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface StatuscakePagespeedCheckAlertConfig {
    alertBigger?: pulumi.Input<number>;
    alertSlower?: pulumi.Input<number>;
    alertSmaller?: pulumi.Input<number>;
}

export interface StatuscakePagespeedCheckMonitoredResource {
    address: pulumi.Input<string>;
}

export interface StatuscakeSslCheckAlertConfig {
    alertAts: pulumi.Input<pulumi.Input<number>[]>;
    onBroken?: pulumi.Input<boolean>;
    onExpiry?: pulumi.Input<boolean>;
    onMixed?: pulumi.Input<boolean>;
    onReminder?: pulumi.Input<boolean>;
}

export interface StatuscakeSslCheckMonitoredResource {
    address: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckDnsCheck {
    dnsIps: pulumi.Input<pulumi.Input<string>[]>;
    dnsServer?: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckHttpCheck {
    basicAuthentication?: pulumi.Input<inputs.StatuscakeUptimeCheckHttpCheckBasicAuthentication>;
    contentMatchers?: pulumi.Input<inputs.StatuscakeUptimeCheckHttpCheckContentMatchers>;
    enableCookies?: pulumi.Input<boolean>;
    finalEndpoint?: pulumi.Input<string>;
    followRedirects?: pulumi.Input<boolean>;
    requestHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    requestMethod?: pulumi.Input<string>;
    requestPayload?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    requestPayloadRaw?: pulumi.Input<string>;
    statusCodes: pulumi.Input<pulumi.Input<string>[]>;
    timeout?: pulumi.Input<number>;
    userAgent?: pulumi.Input<string>;
    validateSsl?: pulumi.Input<boolean>;
}

export interface StatuscakeUptimeCheckHttpCheckBasicAuthentication {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckHttpCheckContentMatchers {
    content: pulumi.Input<string>;
    includeHeaders?: pulumi.Input<boolean>;
    matcher?: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckIcmpCheck {
    enabled?: pulumi.Input<boolean>;
}

export interface StatuscakeUptimeCheckLocation {
    description?: pulumi.Input<string>;
    ipv4?: pulumi.Input<string>;
    ipv6?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    regionCode?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckMonitoredResource {
    address: pulumi.Input<string>;
    host?: pulumi.Input<string>;
}

export interface StatuscakeUptimeCheckTcpCheck {
    authentication?: pulumi.Input<inputs.StatuscakeUptimeCheckTcpCheckAuthentication>;
    port: pulumi.Input<number>;
    protocol?: pulumi.Input<string>;
    timeout?: pulumi.Input<number>;
}

export interface StatuscakeUptimeCheckTcpCheckAuthentication {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
