// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface PagespeedCheckAlertConfig {
    alertBigger?: pulumi.Input<number>;
    alertSlower?: pulumi.Input<number>;
    alertSmaller?: pulumi.Input<number>;
}

export interface PagespeedCheckMonitoredResource {
    address: pulumi.Input<string>;
}

export interface SslCheckAlertConfig {
    alertAts: pulumi.Input<pulumi.Input<number>[]>;
    onBroken?: pulumi.Input<boolean>;
    onExpiry?: pulumi.Input<boolean>;
    onMixed?: pulumi.Input<boolean>;
    onReminder?: pulumi.Input<boolean>;
}

export interface SslCheckMonitoredResource {
    address: pulumi.Input<string>;
    hostname?: pulumi.Input<string>;
}

export interface UptimeCheckDnsCheck {
    dnsIps: pulumi.Input<pulumi.Input<string>[]>;
    dnsServer?: pulumi.Input<string>;
}

export interface UptimeCheckHttpCheck {
    basicAuthentication?: pulumi.Input<inputs.UptimeCheckHttpCheckBasicAuthentication>;
    contentMatchers?: pulumi.Input<inputs.UptimeCheckHttpCheckContentMatchers>;
    enableCookies?: pulumi.Input<boolean>;
    finalEndpoint?: pulumi.Input<string>;
    followRedirects?: pulumi.Input<boolean>;
    requestHeaders?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    requestMethod?: pulumi.Input<string>;
    requestPayload?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    requestPayloadRaw?: pulumi.Input<string>;
    statusCodes: pulumi.Input<pulumi.Input<string>[]>;
    timeout?: pulumi.Input<number>;
    userAgent?: pulumi.Input<string>;
    validateSsl?: pulumi.Input<boolean>;
}

export interface UptimeCheckHttpCheckBasicAuthentication {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface UptimeCheckHttpCheckContentMatchers {
    content: pulumi.Input<string>;
    includeHeaders?: pulumi.Input<boolean>;
    matcher?: pulumi.Input<string>;
}

export interface UptimeCheckIcmpCheck {
    enabled?: pulumi.Input<boolean>;
}

export interface UptimeCheckLocation {
    description?: pulumi.Input<string>;
    ipv4?: pulumi.Input<string>;
    ipv6?: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    regionCode?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
}

export interface UptimeCheckMonitoredResource {
    address: pulumi.Input<string>;
    host?: pulumi.Input<string>;
}

export interface UptimeCheckTcpCheck {
    authentication?: pulumi.Input<inputs.UptimeCheckTcpCheckAuthentication>;
    port: pulumi.Input<number>;
    protocol?: pulumi.Input<string>;
    timeout?: pulumi.Input<number>;
}

export interface UptimeCheckTcpCheckAuthentication {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
