// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GetPagespeedMonitoringLocationsLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface GetUptimeMonitoringLocationsLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface PagespeedCheckAlertConfig {
    alertBigger?: number;
    alertSlower?: number;
    alertSmaller?: number;
}

export interface PagespeedCheckMonitoredResource {
    address: string;
}

export interface SslCheckAlertConfig {
    alertAts: number[];
    onBroken?: boolean;
    onExpiry?: boolean;
    onMixed?: boolean;
    onReminder?: boolean;
}

export interface SslCheckMonitoredResource {
    address: string;
    hostname?: string;
}

export interface UptimeCheckDnsCheck {
    dnsIps: string[];
    dnsServer?: string;
}

export interface UptimeCheckHttpCheck {
    basicAuthentication?: outputs.UptimeCheckHttpCheckBasicAuthentication;
    contentMatchers?: outputs.UptimeCheckHttpCheckContentMatchers;
    enableCookies?: boolean;
    finalEndpoint?: string;
    followRedirects?: boolean;
    requestHeaders?: {[key: string]: string};
    requestMethod?: string;
    requestPayload?: {[key: string]: string};
    requestPayloadRaw?: string;
    statusCodes: string[];
    timeout?: number;
    userAgent?: string;
    validateSsl?: boolean;
}

export interface UptimeCheckHttpCheckBasicAuthentication {
    password: string;
    username: string;
}

export interface UptimeCheckHttpCheckContentMatchers {
    content: string;
    includeHeaders?: boolean;
    matcher?: string;
}

export interface UptimeCheckIcmpCheck {
    enabled?: boolean;
}

export interface UptimeCheckLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface UptimeCheckMonitoredResource {
    address: string;
    host?: string;
}

export interface UptimeCheckTcpCheck {
    authentication?: outputs.UptimeCheckTcpCheckAuthentication;
    port: number;
    protocol?: string;
    timeout?: number;
}

export interface UptimeCheckTcpCheckAuthentication {
    password: string;
    username: string;
}

