// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GetStatuscakePagespeedMonitoringLocationsLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface GetStatuscakeUptimeMonitoringLocationsLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface StatuscakePagespeedCheckAlertConfig {
    alertBigger?: number;
    alertSlower?: number;
    alertSmaller?: number;
}

export interface StatuscakePagespeedCheckMonitoredResource {
    address: string;
}

export interface StatuscakeSslCheckAlertConfig {
    alertAts: number[];
    onBroken?: boolean;
    onExpiry?: boolean;
    onMixed?: boolean;
    onReminder?: boolean;
}

export interface StatuscakeSslCheckMonitoredResource {
    address: string;
    hostname?: string;
}

export interface StatuscakeUptimeCheckDnsCheck {
    dnsIps: string[];
    dnsServer?: string;
}

export interface StatuscakeUptimeCheckHttpCheck {
    basicAuthentication?: outputs.StatuscakeUptimeCheckHttpCheckBasicAuthentication;
    contentMatchers?: outputs.StatuscakeUptimeCheckHttpCheckContentMatchers;
    enableCookies?: boolean;
    finalEndpoint?: string;
    followRedirects?: boolean;
    requestHeaders?: {[key: string]: string};
    requestMethod?: string;
    requestPayload?: {[key: string]: string};
    requestPayloadRaw?: string;
    statusCodes: string[];
    timeout?: number;
    userAgent?: string;
    validateSsl?: boolean;
}

export interface StatuscakeUptimeCheckHttpCheckBasicAuthentication {
    password: string;
    username: string;
}

export interface StatuscakeUptimeCheckHttpCheckContentMatchers {
    content: string;
    includeHeaders?: boolean;
    matcher?: string;
}

export interface StatuscakeUptimeCheckIcmpCheck {
    enabled?: boolean;
}

export interface StatuscakeUptimeCheckLocation {
    description: string;
    ipv4: string;
    ipv6: string;
    region: string;
    regionCode: string;
    status: string;
}

export interface StatuscakeUptimeCheckMonitoredResource {
    address: string;
    host?: string;
}

export interface StatuscakeUptimeCheckTcpCheck {
    authentication?: outputs.StatuscakeUptimeCheckTcpCheckAuthentication;
    port: number;
    protocol?: string;
    timeout?: number;
}

export interface StatuscakeUptimeCheckTcpCheckAuthentication {
    password: string;
    username: string;
}

