// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class StatuscakeSslCheckAlertConfigArgs : Pulumi.ResourceArgs
    {
        [Input("alertAts", required: true)]
        private InputList<int>? _alertAts;
        public InputList<int> AlertAts
        {
            get => _alertAts ?? (_alertAts = new InputList<int>());
            set => _alertAts = value;
        }

        [Input("onBroken")]
        public Input<bool>? OnBroken { get; set; }

        [Input("onExpiry")]
        public Input<bool>? OnExpiry { get; set; }

        [Input("onMixed")]
        public Input<bool>? OnMixed { get; set; }

        [Input("onReminder")]
        public Input<bool>? OnReminder { get; set; }

        public StatuscakeSslCheckAlertConfigArgs()
        {
        }
    }
}
