// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Statuscake.Inputs
{

    public sealed class UptimeCheckHttpCheckGetArgs : Pulumi.ResourceArgs
    {
        [Input("basicAuthentication")]
        public Input<Inputs.UptimeCheckHttpCheckBasicAuthenticationGetArgs>? BasicAuthentication { get; set; }

        [Input("contentMatchers")]
        public Input<Inputs.UptimeCheckHttpCheckContentMatchersGetArgs>? ContentMatchers { get; set; }

        [Input("enableCookies")]
        public Input<bool>? EnableCookies { get; set; }

        [Input("finalEndpoint")]
        public Input<string>? FinalEndpoint { get; set; }

        [Input("followRedirects")]
        public Input<bool>? FollowRedirects { get; set; }

        [Input("requestHeaders")]
        private InputMap<string>? _requestHeaders;
        public InputMap<string> RequestHeaders
        {
            get => _requestHeaders ?? (_requestHeaders = new InputMap<string>());
            set => _requestHeaders = value;
        }

        [Input("requestMethod")]
        public Input<string>? RequestMethod { get; set; }

        [Input("requestPayload")]
        private InputMap<string>? _requestPayload;
        public InputMap<string> RequestPayload
        {
            get => _requestPayload ?? (_requestPayload = new InputMap<string>());
            set => _requestPayload = value;
        }

        [Input("requestPayloadRaw")]
        public Input<string>? RequestPayloadRaw { get; set; }

        [Input("statusCodes", required: true)]
        private InputList<string>? _statusCodes;
        public InputList<string> StatusCodes
        {
            get => _statusCodes ?? (_statusCodes = new InputList<string>());
            set => _statusCodes = value;
        }

        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        [Input("userAgent")]
        public Input<string>? UserAgent { get; set; }

        [Input("validateSsl")]
        public Input<bool>? ValidateSsl { get; set; }

        public UptimeCheckHttpCheckGetArgs()
        {
        }
    }
}
