name: main

on:
  push:
    branches:
      - main
      - "feature/**"
      - "dependabot/**"
    tags-ignore:
      - v*
  workflow_dispatch:

jobs:
  prerequisites:
    uses: pulumiverse/infra/.github/workflows/provider-prerequisites.yaml@main
    with:
      provider: statuscake
  build:
    needs: prerequisites
    uses: pulumiverse/infra/.github/workflows/provider-build-sdk.yaml@main
    with:
      provider: statuscake
