// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getPagespeedMonitoringLocations(args?: GetPagespeedMonitoringLocationsArgs, opts?: pulumi.InvokeOptions): Promise<GetPagespeedMonitoringLocationsResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("statuscake:index/getPagespeedMonitoringLocations:getPagespeedMonitoringLocations", {
        "regionCode": args.regionCode,
    }, opts);
}

/**
 * A collection of arguments for invoking getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsArgs {
    regionCode?: string;
}

/**
 * A collection of values returned by getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly locations: outputs.GetPagespeedMonitoringLocationsLocation[];
    readonly regionCode?: string;
}

export function getPagespeedMonitoringLocationsOutput(args?: GetPagespeedMonitoringLocationsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPagespeedMonitoringLocationsResult> {
    return pulumi.output(args).apply(a => getPagespeedMonitoringLocations(a, opts))
}

/**
 * A collection of arguments for invoking getPagespeedMonitoringLocations.
 */
export interface GetPagespeedMonitoringLocationsOutputArgs {
    regionCode?: pulumi.Input<string>;
}
