// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getStatuscakeContactGroup";
export * from "./getStatuscakePagespeedMonitoringLocations";
export * from "./getStatuscakeUptimeMonitoringLocations";
export * from "./provider";
export * from "./statuscakeContactGroup";
export * from "./statuscakeMaintenanceWindow";
export * from "./statuscakePagespeedCheck";
export * from "./statuscakeSslCheck";
export * from "./statuscakeUptimeCheck";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { StatuscakeContactGroup } from "./statuscakeContactGroup";
import { StatuscakeMaintenanceWindow } from "./statuscakeMaintenanceWindow";
import { StatuscakePagespeedCheck } from "./statuscakePagespeedCheck";
import { StatuscakeSslCheck } from "./statuscakeSslCheck";
import { StatuscakeUptimeCheck } from "./statuscakeUptimeCheck";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "statuscake:index/statuscakeContactGroup:StatuscakeContactGroup":
                return new StatuscakeContactGroup(name, <any>undefined, { urn })
            case "statuscake:index/statuscakeMaintenanceWindow:StatuscakeMaintenanceWindow":
                return new StatuscakeMaintenanceWindow(name, <any>undefined, { urn })
            case "statuscake:index/statuscakePagespeedCheck:StatuscakePagespeedCheck":
                return new StatuscakePagespeedCheck(name, <any>undefined, { urn })
            case "statuscake:index/statuscakeSslCheck:StatuscakeSslCheck":
                return new StatuscakeSslCheck(name, <any>undefined, { urn })
            case "statuscake:index/statuscakeUptimeCheck:StatuscakeUptimeCheck":
                return new StatuscakeUptimeCheck(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("statuscake", "index/statuscakeContactGroup", _module)
pulumi.runtime.registerResourceModule("statuscake", "index/statuscakeMaintenanceWindow", _module)
pulumi.runtime.registerResourceModule("statuscake", "index/statuscakePagespeedCheck", _module)
pulumi.runtime.registerResourceModule("statuscake", "index/statuscakeSslCheck", _module)
pulumi.runtime.registerResourceModule("statuscake", "index/statuscakeUptimeCheck", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("statuscake", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:statuscake") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
