// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MaintenanceWindow extends pulumi.CustomResource {
    /**
     * Get an existing MaintenanceWindow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MaintenanceWindowState, opts?: pulumi.CustomResourceOptions): MaintenanceWindow {
        return new MaintenanceWindow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'statuscake:index/maintenanceWindow:MaintenanceWindow';

    /**
     * Returns true if the given object is an instance of MaintenanceWindow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MaintenanceWindow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MaintenanceWindow.__pulumiType;
    }

    /**
     * End of the maintenance window (RFC3339 format)
     */
    public readonly end!: pulumi.Output<string>;
    /**
     * Name of the maintenance window
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * How often the maintenance window should occur
     */
    public readonly repeatInterval!: pulumi.Output<string | undefined>;
    /**
     * Start of the maintenance window (RFC3339 format)
     */
    public readonly start!: pulumi.Output<string>;
    /**
     * List of tags used to include matching uptime checks in this maintenance window
     */
    public readonly tags!: pulumi.Output<string[] | undefined>;
    /**
     * List of uptime check IDs explicitly included in this maintenance window
     */
    public readonly tests!: pulumi.Output<string[] | undefined>;
    /**
     * Standard timezone associated with this maintenance window
     */
    public readonly timezone!: pulumi.Output<string>;

    /**
     * Create a MaintenanceWindow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MaintenanceWindowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MaintenanceWindowArgs | MaintenanceWindowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MaintenanceWindowState | undefined;
            resourceInputs["end"] = state ? state.end : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["repeatInterval"] = state ? state.repeatInterval : undefined;
            resourceInputs["start"] = state ? state.start : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["tests"] = state ? state.tests : undefined;
            resourceInputs["timezone"] = state ? state.timezone : undefined;
        } else {
            const args = argsOrState as MaintenanceWindowArgs | undefined;
            if ((!args || args.end === undefined) && !opts.urn) {
                throw new Error("Missing required property 'end'");
            }
            if ((!args || args.start === undefined) && !opts.urn) {
                throw new Error("Missing required property 'start'");
            }
            if ((!args || args.timezone === undefined) && !opts.urn) {
                throw new Error("Missing required property 'timezone'");
            }
            resourceInputs["end"] = args ? args.end : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["repeatInterval"] = args ? args.repeatInterval : undefined;
            resourceInputs["start"] = args ? args.start : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["tests"] = args ? args.tests : undefined;
            resourceInputs["timezone"] = args ? args.timezone : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MaintenanceWindow.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MaintenanceWindow resources.
 */
export interface MaintenanceWindowState {
    /**
     * End of the maintenance window (RFC3339 format)
     */
    end?: pulumi.Input<string>;
    /**
     * Name of the maintenance window
     */
    name?: pulumi.Input<string>;
    /**
     * How often the maintenance window should occur
     */
    repeatInterval?: pulumi.Input<string>;
    /**
     * Start of the maintenance window (RFC3339 format)
     */
    start?: pulumi.Input<string>;
    /**
     * List of tags used to include matching uptime checks in this maintenance window
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of uptime check IDs explicitly included in this maintenance window
     */
    tests?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Standard timezone associated with this maintenance window
     */
    timezone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a MaintenanceWindow resource.
 */
export interface MaintenanceWindowArgs {
    /**
     * End of the maintenance window (RFC3339 format)
     */
    end: pulumi.Input<string>;
    /**
     * Name of the maintenance window
     */
    name?: pulumi.Input<string>;
    /**
     * How often the maintenance window should occur
     */
    repeatInterval?: pulumi.Input<string>;
    /**
     * Start of the maintenance window (RFC3339 format)
     */
    start: pulumi.Input<string>;
    /**
     * List of tags used to include matching uptime checks in this maintenance window
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of uptime check IDs explicitly included in this maintenance window
     */
    tests?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Standard timezone associated with this maintenance window
     */
    timezone: pulumi.Input<string>;
}
